package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;


/**
 * AbilityMaster generated by hbm2java
 */

public class AbilityMaster  implements java.io.Serializable {


    // Fields    

     private Short abilId;
     private String abilDesc;
     private Integer version;
     private Set abilSkillRels = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbilityMaster() {
    }

	/** minimal constructor */
    public AbilityMaster(Short abilId, String abilDesc) {
        this.abilId = abilId;
        this.abilDesc = abilDesc;
    }
    
    /** full constructor */
    public AbilityMaster(Short abilId, String abilDesc, Integer version, Set abilSkillRels) {
        this.abilId = abilId;
        this.abilDesc = abilDesc;
        this.version = version;
        this.abilSkillRels = abilSkillRels;
    }
    

   
    // Property accessors

    public Short getAbilId() {
        return this.abilId;
    }
    
    public void setAbilId(Short abilId) {
        this.abilId = abilId;
    }

    public String getAbilDesc() {
        return this.abilDesc;
    }
    
    public void setAbilDesc(String abilDesc) {
        this.abilDesc = abilDesc;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set getAbilSkillRels() {
        return this.abilSkillRels;
    }
    
    public void setAbilSkillRels(Set abilSkillRels) {
        this.abilSkillRels = abilSkillRels;
    }
   








}
