package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3



/**
 * AbilitySkillRel generated by hbm2java
 */

public class AbilitySkillRel  implements java.io.Serializable {


    // Fields    

     private AbilitySkillRelKey comp_id;
     private Integer version;
     private AbilityMaster abilMa;
     private SkillMaster skillMa;


    // Constructors

    /** default constructor */
    public AbilitySkillRel() {
    }

	/** minimal constructor */
    public AbilitySkillRel(AbilitySkillRelKey comp_id) {
        this.comp_id = comp_id;
    }
    
    /** full constructor */
    public AbilitySkillRel(AbilitySkillRelKey comp_id, Integer version, AbilityMaster abilMa, SkillMaster skillMa) {
        this.comp_id = comp_id;
        this.version = version;
        this.abilMa = abilMa;
        this.skillMa = skillMa;
    }
    

   
    // Property accessors

    public AbilitySkillRelKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(AbilitySkillRelKey comp_id) {
        this.comp_id = comp_id;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public AbilityMaster getAbilMa() {
        return this.abilMa;
    }
    
    public void setAbilMa(AbilityMaster abilMa) {
        this.abilMa = abilMa;
    }

    public SkillMaster getSkillMa() {
        return this.skillMa;
    }
    
    public void setSkillMa(SkillMaster skillMa) {
        this.skillMa = skillMa;
    }
   








}
