package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:58 PM by Hibernate Tools 3.1.0 beta3



/**
 * AbilitySkillRelKey generated by hbm2java
 */

public class AbilitySkillRelKey  implements java.io.Serializable {


    // Fields    

     private Short abilId;
     private Short skillId;


    // Constructors

    /** default constructor */
    public AbilitySkillRelKey() {
    }

    
    /** full constructor */
    public AbilitySkillRelKey(Short abilId, Short skillId) {
        this.abilId = abilId;
        this.skillId = skillId;
    }
    

   
    // Property accessors

    public Short getAbilId() {
        return this.abilId;
    }
    
    public void setAbilId(Short abilId) {
        this.abilId = abilId;
    }

    public Short getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Short skillId) {
        this.skillId = skillId;
    }
   








}
