package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3

import java.util.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;


/**
 * AcctMaster generated by hbm2java
 */

public class AcctMaster  implements java.io.Serializable {


    // Fields    

     private String acctId;
     private String acctTyp;
     private Date crtDt;
     private String acctStat;
     private Integer version;
     private CompanyAcctMaster coAcctMa;
     private Set testSesMas = new HashSet(0);


    // Constructors

    /** default constructor */
    public AcctMaster() {
    }

	/** minimal constructor */
    public AcctMaster(String acctId, String acctTyp, Date crtDt) {
        this.acctId = acctId;
        this.acctTyp = acctTyp;
        this.crtDt = crtDt;
    }
    
    /** full constructor */
    public AcctMaster(String acctId, String acctTyp, Date crtDt, String acctStat, Integer version, CompanyAcctMaster coAcctMa, Set testSesMas) {
        this.acctId = acctId;
        this.acctTyp = acctTyp;
        this.crtDt = crtDt;
        this.acctStat = acctStat;
        this.version = version;
        this.coAcctMa = coAcctMa;
        this.testSesMas = testSesMas;
    }
    

   
    // Property accessors

    public String getAcctId() {
        return this.acctId;
    }
    
    public void setAcctId(String acctId) {
        this.acctId = acctId;
    }

    public String getAcctTyp() {
        return this.acctTyp;
    }
    
    public void setAcctTyp(String acctTyp) {
        this.acctTyp = acctTyp;
    }


    /**
	 * @return Returns the crtDt.
	 */
	public Date getCrtDt() {
		return crtDt;
	}

	/**
	 * @param crtDt The crtDt to set.
	 */
	public void setCrtDt(Date crtDt) {
		this.crtDt = crtDt;
	}

	public String getAcctStat() {
        return this.acctStat;
    }
    
    public void setAcctStat(String acctStat) {
        this.acctStat = acctStat;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public CompanyAcctMaster getCoAcctMa() {
        return this.coAcctMa;
    }
    
    public void setCoAcctMa(CompanyAcctMaster coAcctMa) {
        this.coAcctMa = coAcctMa;
    }

    public Set getTestSesMas() {
        return this.testSesMas;
    }
    
    public void setTestSesMas(Set testSesMas) {
        this.testSesMas = testSesMas;
    }
   








}
