package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;


/**
 * ActvRolMaster generated by hbm2java
 */

public class ActvRolMaster  implements java.io.Serializable {


    // Fields    

     private Short actvRolId;
     private String rolDesc;
     private Integer version;
     private Set coUsrMas = new HashSet(0);


    // Constructors

    /** default constructor */
    public ActvRolMaster() {
    }

	/** minimal constructor */
    public ActvRolMaster(Short actvRolId, String rolDesc) {
        this.actvRolId = actvRolId;
        this.rolDesc = rolDesc;
    }
    
    /** full constructor */
    public ActvRolMaster(Short actvRolId, String rolDesc, Integer version, Set coUsrMas) {
        this.actvRolId = actvRolId;
        this.rolDesc = rolDesc;
        this.version = version;
        this.coUsrMas = coUsrMas;
    }
    

   
    // Property accessors

    public Short getActvRolId() {
        return this.actvRolId;
    }
    
    public void setActvRolId(Short actvRolId) {
        this.actvRolId = actvRolId;
    }

    public String getRolDesc() {
        return this.rolDesc;
    }
    
    public void setRolDesc(String rolDesc) {
        this.rolDesc = rolDesc;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set getCoUsrMas() {
        return this.coUsrMas;
    }
    
    public void setCoUsrMas(Set coUsrMas) {
        this.coUsrMas = coUsrMas;
    }
   








}
