package com.mgmtassessment.execmap.data.dao.types;

// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * CompanyAcctMaster generated by hbm2java.
 */

public class CompanyAcctMaster implements java.io.Serializable {

    // Fields

    private String            acctId;

    private String            acctTyp;

    private String            acctStat;

    private Date              crtDt;

    private String            coName;

    private String            coInfo;

    private String            cobraInfo;

    private String            coAddr1;

    private String            coAddr2;

    private String            coCity;

    private String            coState;

    private String            coCountry;

    private String            coZip;

    private String            coEmail;

    private String            tocName;

    private String            tocEmail;

    private Integer           version;

    private AcctMaster        acctMa;

    private Set               coGrpMas = new HashSet(0);

    private ReportMaster      rptMa;

    private CompanyUserMaster coUsrMa;

    private String            totalUsers;

    // Constructors

    /**
     * @return Returns the totalUsers.
     */
    public String getTotalUsers() {
        return totalUsers;
    }

    /**
     * @param totalUsers
     *            The totalUsers to set.
     */
    public void setTotalUsers(String totalUsers) {
        this.totalUsers = totalUsers;
    }

    /** default constructor */
    public CompanyAcctMaster ( ) {
    }

    /** minimal constructor */
    public CompanyAcctMaster ( String acctId, String acctTyp, Date crtDt,
            String coName, String coAddr1, String coCity, String coCountry,
            String coEmail, String tocName, String tocEmail, AcctMaster acctMa ) {
        this.acctId = acctId;
        this.acctTyp = acctTyp;
        this.crtDt = crtDt;
        this.coName = coName;
        this.coAddr1 = coAddr1;
        this.coCity = coCity;
        this.coCountry = coCountry;
        this.coEmail = coEmail;
        this.tocName = tocName;
        this.tocEmail = tocEmail;
        this.acctMa = acctMa;

    }

    /** full constructor */
    public CompanyAcctMaster ( String acctId, String acctTyp, String acctStat,
            Date crtDt, String coName, String coInfo, String cobraInfo,
            String coAddr1, String coAddr2, String coCity, String coState,
            String coCountry, String coZip, String coEmail, String tocName,
            String tocEmail, Integer version, AcctMaster acctMa, Set coGrpMas,
            ReportMaster rptMa, CompanyUserMaster coUsrMa ) {
        this.acctId = acctId;
        this.acctTyp = acctTyp;
        this.acctStat = acctStat;
        this.crtDt = crtDt;
        this.coName = coName;
        this.coInfo = coInfo;
        this.cobraInfo = cobraInfo;
        this.coAddr1 = coAddr1;
        this.coAddr2 = coAddr2;
        this.coCity = coCity;
        this.coState = coState;
        this.coCountry = coCountry;
        this.coZip = coZip;
        this.coEmail = coEmail;
        this.tocName = tocName;
        this.tocEmail = tocEmail;
        this.version = version;
        this.acctMa = acctMa;
        this.coGrpMas = coGrpMas;
        this.rptMa = rptMa;
        this.coUsrMa = coUsrMa;

    }

    // Property accessors

    public String getAcctId() {
        return this.acctId;
    }

    public void setAcctId(String acctId) {
        this.acctId = acctId;
    }

    public String getAcctTyp() {
        return this.acctTyp;
    }

    public void setAcctTyp(String acctTyp) {
        this.acctTyp = acctTyp;
    }

    public String getAcctStat() {
        return this.acctStat;
    }

    public void setAcctStat(String acctStat) {
        this.acctStat = acctStat;
    }

    /**
     * @return Returns the crtDt.
     */
    public Date getCrtDt() {
        return crtDt;
    }

    /**
     * @param crtDt
     *            The crtDt to set.
     */
    public void setCrtDt(Date crtDt) {
        this.crtDt = crtDt;
    }

    public String getCoName() {
        return this.coName;
    }

    public void setCoName(String coName) {
        this.coName = coName;
    }

    public String getCoInfo() {
        return this.coInfo;
    }

    public void setCoInfo(String coInfo) {
        this.coInfo = coInfo;
    }

    public String getCobraInfo() {
        return this.cobraInfo;
    }

    public void setCobraInfo(String cobraInfo) {
        this.cobraInfo = cobraInfo;
    }

    public String getCoAddr1() {
        return this.coAddr1;
    }

    public void setCoAddr1(String coAddr1) {
        this.coAddr1 = coAddr1;
    }

    public String getCoAddr2() {
        return this.coAddr2;
    }

    public void setCoAddr2(String coAddr2) {
        this.coAddr2 = coAddr2;
    }

    public String getCoCity() {
        return this.coCity;
    }

    public void setCoCity(String coCity) {
        this.coCity = coCity;
    }

    public String getCoState() {
        return this.coState;
    }

    public void setCoState(String coState) {
        this.coState = coState;
    }

    public String getCoCountry() {
        return this.coCountry;
    }

    public void setCoCountry(String coCountry) {
        this.coCountry = coCountry;
    }

    public String getCoZip() {
        return this.coZip;
    }

    public void setCoZip(String coZip) {
        this.coZip = coZip;
    }

    public String getCoEmail() {
        return this.coEmail;
    }

    public void setCoEmail(String coEmail) {
        this.coEmail = coEmail;
    }

    public String getTocName() {
        return this.tocName;
    }

    public void setTocName(String tocName) {
        this.tocName = tocName;
    }

    public String getTocEmail() {
        return this.tocEmail;
    }

    public void setTocEmail(String tocEmail) {
        this.tocEmail = tocEmail;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public AcctMaster getAcctMa() {
        return this.acctMa;
    }

    public void setAcctMa(AcctMaster acctMa) {
        this.acctMa = acctMa;
    }

    public Set getCoGrpMas() {
        return this.coGrpMas;
    }

    public void setCoGrpMas(Set coGrpMas) {
        this.coGrpMas = coGrpMas;
    }

    public ReportMaster getRptMa() {
        return this.rptMa;
    }

    public void setRptMa(ReportMaster rptMa) {
        this.rptMa = rptMa;
    }

    public CompanyUserMaster getCoUsrMa() {
        return this.coUsrMa;
    }

    public void setCoUsrMa(CompanyUserMaster coUsrMa) {
        this.coUsrMa = coUsrMa;
    }
    
    
    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( !(other.equals(this)) ) return false;
        return new EqualsBuilder()
            .append(this.getAcctId(), this.getCoName())
            .isEquals();
    }

    public int hashCode() {
        return new HashCodeBuilder()
            .append(getAcctId())
            .toHashCode();
    }

}
