package com.mgmtassessment.execmap.data.dao.types;


import java.util.HashSet;
import java.util.Set;


/**
 * CompanyUserMaster generated by hbm2java
 */

public class CompanyUserMaster  implements java.io.Serializable {


    // Fields    

     private CompanyUserMasterKey comp_id;
     private String passwd;
     private String firstName;
     private String lastName;
     private String usrEmail;
     private String notes1;
     private String notes2;
     private String startFlg;
     private String usrStat;
     private String reminderPhrase;
     private Integer version;
     private ActvRolMaster actvRolMa;
     private CompanyGroupMaster coGrpMa;
     private Set coAcctMas = new HashSet(0);
     private Set coGrpMas = new HashSet(0);
     private String grpId;
     private Integer acctLocked;
    // Constructors

    /** default constructor */
    public CompanyUserMaster() {
    }

	/** minimal constructor */
    public CompanyUserMaster(CompanyUserMasterKey comp_id, String passwd, String firstName,String lastName, String usrEmail, String startFlg, String usrStat, String grpId) {
        this.comp_id = comp_id;
        this.passwd = passwd;
        this.firstName = firstName;
        this.lastName = lastName;
        this.usrEmail = usrEmail;
        this.startFlg = startFlg;
        this.usrStat = usrStat;
        this.grpId = grpId;
    }
    
    /** full constructor */
    public CompanyUserMaster(CompanyUserMasterKey comp_id, String passwd, String usrName, String firstName,String lastName, String notes1, String notes2, String startFlg, String usrStat, String reminderPhrase, Integer version, ActvRolMaster actvRolMa, CompanyGroupMaster coGrpMa, Set coAcctMas, Set coGrpMas, String grpId,Integer acctLocked) {
        this.comp_id = comp_id;
        this.passwd = passwd;
        this.firstName = firstName;
        this.lastName = lastName;
        this.usrEmail = usrEmail;
        this.notes1 = notes1;
        this.notes2 = notes2;
        this.startFlg = startFlg;
        this.usrStat = usrStat;
        this.reminderPhrase = reminderPhrase;
        this.version = version;
        this.actvRolMa = actvRolMa;
        this.coGrpMa = coGrpMa;
        this.coAcctMas = coAcctMas;
        this.coGrpMas = coGrpMas;
        this.grpId = grpId;
        this.acctLocked = acctLocked ;
    }
    

   
    // Property accessors

    public CompanyUserMasterKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(CompanyUserMasterKey comp_id) {
        this.comp_id = comp_id;
    }

    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
	 * @return Returns the firstName.
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * @param firstName The firstName to set.
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @return Returns the lastName.
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * @param lastName The lastName to set.
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUsrEmail() {
        return this.usrEmail;
    }
    
    public void setUsrEmail(String usrEmail) {
        this.usrEmail = usrEmail;
    }

    public String getNotes1() {
        return this.notes1;
    }
    
    public void setNotes1(String notes1) {
        this.notes1 = notes1;
    }

    public String getNotes2() {
        return this.notes2;
    }
    
    public void setNotes2(String notes2) {
        this.notes2 = notes2;
    }

    public String getStartFlg() {
        return this.startFlg;
    }
    
    public void setStartFlg(String startFlg) {
        this.startFlg = startFlg;
    }

    public String getUsrStat() {
        return this.usrStat;
    }
    
    public void setUsrStat(String usrStat) {
        this.usrStat = usrStat;
    }

    public String getReminderPhrase() {
        return this.reminderPhrase;
    }
    
    public void setReminderPhrase(String reminderPhrase) {
        this.reminderPhrase = reminderPhrase;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public ActvRolMaster getActvRolMa() {
        return this.actvRolMa;
    }
    
    public void setActvRolMa(ActvRolMaster actvRolMa) {
        this.actvRolMa = actvRolMa;
    }

    public CompanyGroupMaster getCoGrpMa() {
        return this.coGrpMa;
    }
    
    public void setCoGrpMa(CompanyGroupMaster coGrpMa) {
        this.coGrpMa = coGrpMa;
    }

    public Set getCoAcctMas() {
        return this.coAcctMas;
    }
    
    public void setCoAcctMas(Set coAcctMas) {
        this.coAcctMas = coAcctMas;
    }

    public Set getCoGrpMas() {
        return this.coGrpMas;
    }
    
    public void setCoGrpMas(Set coGrpMas) {
        this.coGrpMas = coGrpMas;
    }

	/**
	 * @return Returns the grpId.
	 */
	public String getGrpId() {
		return grpId;
	}

	/**
	 * @param grpId The grpId to set.
	 */
	public void setGrpId(String grpId) {
		this.grpId = grpId;
	}

    /**
     * @return Returns the acctLocked.
     */
    public Integer getAcctLocked() {
        return acctLocked;
    }

    /**
     * @param acctLocked The acctLocked to set.
     */
    public void setAcctLocked(Integer acctLocked) {
        this.acctLocked = acctLocked;
    }

   
   








}
