package com.mgmtassessment.execmap.data.dao.types;

// Generated Aug 3, 2006 6:56:57 PM by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;

/**
 * CompanyGroupMaster generated by hbm2java
 */

public class CompanyGroupMaster implements java.io.Serializable {

    // Fields

    private CompanyGroupMasterKey comp_id;

    private String                grpInfo;

    private String                grpStat;

    private String                grpEmail;

    private Integer               version;

    private CompanyAcctMaster     coAcctMa;

    private Set                   coUsrMas = new HashSet(0);

    private CompanyUserMaster     coUsrMa;

    // Constructors

    /** default constructor */
    public CompanyGroupMaster ( ) {
    }

    /** minimal constructor */
    public CompanyGroupMaster ( CompanyGroupMasterKey comp_id, String grpStat ) {
        this.comp_id = comp_id;
        this.grpStat = grpStat;

    }

    /** full constructor */
    public CompanyGroupMaster ( CompanyGroupMasterKey comp_id, String grpInfo,
            String grpStat, String grpEmail, Integer version,
            CompanyAcctMaster coAcctMa, Set coUsrMas, CompanyUserMaster coUsrMa ) {
        this.comp_id = comp_id;
        this.grpInfo = grpInfo;
        this.grpStat = grpStat;
        this.grpEmail = grpEmail;
        this.version = version;
        this.coAcctMa = coAcctMa;
        this.coUsrMas = coUsrMas;
        this.coUsrMa = coUsrMa;
    }

    // Property accessors

    public CompanyGroupMasterKey getComp_id() {
        return this.comp_id;
    }

    public void setComp_id(CompanyGroupMasterKey comp_id) {
        this.comp_id = comp_id;
    }

    public String getGrpInfo() {
        return this.grpInfo;
    }

    public void setGrpInfo(String grpInfo) {
        this.grpInfo = grpInfo;
    }

    public String getGrpStat() {
        return this.grpStat;
    }

    public void setGrpStat(String grpStat) {
        this.grpStat = grpStat;
    }

    public String getGrpEmail() {
        return this.grpEmail;
    }

    public void setGrpEmail(String grpEmail) {
        this.grpEmail = grpEmail;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public CompanyAcctMaster getCoAcctMa() {
        return this.coAcctMa;
    }

    public void setCoAcctMa(CompanyAcctMaster coAcctMa) {
        this.coAcctMa = coAcctMa;
    }

    public Set getCoUsrMas() {
        return this.coUsrMas;
    }

    public void setCoUsrMas(Set coUsrMas) {
        this.coUsrMas = coUsrMas;
    }

    public CompanyUserMaster getCoUsrMa() {
        return this.coUsrMa;
    }

    public void setCoUsrMa(CompanyUserMaster coUsrMa) {
        this.coUsrMa = coUsrMa;
    }

}
