package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3



/**
 * ExecmapSysMa generated by hbm2java
 */

public class ExecmapSysMaster  implements java.io.Serializable {


    // Fields    
     private short sysMasId;
     private int lstAcctNo;
     private short testDur;
     private String intlcAcctId;
     private String intlcUsrId;
     private String intlcPasswd;
     private String emailServerName;
     private String emailServerPort;
     private String emailServerUserid;
     private String emailServerPassword;
     private Integer version;


    // Constructors

    /** default constructor */
    public ExecmapSysMaster() {
    }

    
    /** full constructor */
    public ExecmapSysMaster(short sysMasId,int lstAcctNo, short testDur, String intlcAcctId, String intlcUsrId, String intlcPasswd, String emailServerName, String emailServerPort, String emailServerUserid, String emailServerPassword, Integer version) {
        this.sysMasId = sysMasId;
        this.lstAcctNo = lstAcctNo;
        this.testDur = testDur;
        this.intlcAcctId = intlcAcctId;
        this.intlcUsrId = intlcUsrId;
        this.intlcPasswd = intlcPasswd;
        this.emailServerName = emailServerName;
        this.emailServerPort = emailServerPort;
        this.emailServerUserid = emailServerUserid;
        this.emailServerPassword = emailServerPassword;
        this.version = version;
    }
    

   
    // Property accessors

    public int getLstAcctNo() {
        return this.lstAcctNo;
    }
    
    public void setLstAcctNo(int lstAcctNo) {
        this.lstAcctNo = lstAcctNo;
    }

    public short getTestDur() {
        return this.testDur;
    }
    
    public void setTestDur(short testDur) {
        this.testDur = testDur;
    }

    public String getIntlcAcctId() {
        return this.intlcAcctId;
    }
    
    public void setIntlcAcctId(String intlcAcctId) {
        this.intlcAcctId = intlcAcctId;
    }

    public String getIntlcUsrId() {
        return this.intlcUsrId;
    }
    
    public void setIntlcUsrId(String intlcUsrId) {
        this.intlcUsrId = intlcUsrId;
    }

    public String getIntlcPasswd() {
        return this.intlcPasswd;
    }
    
    public void setIntlcPasswd(String intlcPasswd) {
        this.intlcPasswd = intlcPasswd;
    }

    public String getEmailServerName() {
        return this.emailServerName;
    }
    
    public void setEmailServerName(String emailServerName) {
        this.emailServerName = emailServerName;
    }

    public String getEmailServerPort() {
        return this.emailServerPort;
    }
    
    public void setEmailServerPort(String emailServerPort) {
        this.emailServerPort = emailServerPort;
    }

    public String getEmailServerUserid() {
        return this.emailServerUserid;
    }
    
    public void setEmailServerUserid(String emailServerUserid) {
        this.emailServerUserid = emailServerUserid;
    }

    public String getEmailServerPassword() {
        return this.emailServerPassword;
    }
    
    public void setEmailServerPassword(String emailServerPassword) {
        this.emailServerPassword = emailServerPassword;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }


    /**
     * @return Returns the sysMasId.
     */
    public short getSysMasId() {
        return sysMasId;
    }


    /**
     * @param sysMasId The sysMasId to set.
     */
    public void setSysMasId(short sysMasId) {
        this.sysMasId = sysMasId;
    }
   








}
