package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;


/**
 * ReportMaster generated by hbm2java
 */

public class ReportMaster  implements java.io.Serializable {


    // Fields    

     private Short rptId;
     private String rptDesc;
     private Integer version;
     private Set coAcctMas = new HashSet(0);
     private Set rptParaDets = new HashSet(0);


    // Constructors

    /** default constructor */
    public ReportMaster() {
    }

	/** minimal constructor */
    public ReportMaster(Short rptId, String rptDesc) {
        this.rptId = rptId;
        this.rptDesc = rptDesc;
    }
    
    /** full constructor */
    public ReportMaster(Short rptId, String rptDesc, Integer version, Set coAcctMas, Set rptParaDets) {
        this.rptId = rptId;
        this.rptDesc = rptDesc;
        this.version = version;
        this.coAcctMas = coAcctMas;
        this.rptParaDets = rptParaDets;
    }
    

   
    // Property accessors

    public Short getRptId() {
        return this.rptId;
    }
    
    public void setRptId(Short rptId) {
        this.rptId = rptId;
    }

    public String getRptDesc() {
        return this.rptDesc;
    }
    
    public void setRptDesc(String rptDesc) {
        this.rptDesc = rptDesc;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set getCoAcctMas() {
        return this.coAcctMas;
    }
    
    public void setCoAcctMas(Set coAcctMas) {
        this.coAcctMas = coAcctMas;
    }

    public Set getRptParaDets() {
        return this.rptParaDets;
    }
    
    public void setRptParaDets(Set rptParaDets) {
        this.rptParaDets = rptParaDets;
    }
   








}
