package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3



/**
 * RptParaDet generated by hbm2java
 */

public class RptParaDet  implements java.io.Serializable {


    // Fields    

     private RptParaDetKey comp_id;
     private String paraId;
     private Integer version;
     private ReportMaster rptMa;


    // Constructors

    /** default constructor */
    public RptParaDet() {
    }

	/** minimal constructor */
    public RptParaDet(RptParaDetKey comp_id, String paraId) {
        this.comp_id = comp_id;
        this.paraId = paraId;
    }
    
    /** full constructor */
    public RptParaDet(RptParaDetKey comp_id, String paraId, Integer version, ReportMaster rptMa) {
        this.comp_id = comp_id;
        this.paraId = paraId;
        this.version = version;
        this.rptMa = rptMa;
    }
    

   
    // Property accessors

    public RptParaDetKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(RptParaDetKey comp_id) {
        this.comp_id = comp_id;
    }

    public String getParaId() {
        return this.paraId;
    }
    
    public void setParaId(String paraId) {
        this.paraId = paraId;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public ReportMaster getRptMa() {
        return this.rptMa;
    }
    
    public void setRptMa(ReportMaster rptMa) {
        this.rptMa = rptMa;
    }
   








}
