package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:58 PM by Hibernate Tools 3.1.0 beta3



/**
 * SkillLvlTriRelKey generated by hbm2java
 */

public class SkillLvlTriRelKey  implements java.io.Serializable {


    // Fields    

     private Short skillId;
     private String triId;
     private Short levelNo;


    // Constructors

    /** default constructor */
    public SkillLvlTriRelKey() {
    }

    
    /** full constructor */
    public SkillLvlTriRelKey(Short skillId, String triId, Short levelNo) {
        this.skillId = skillId;
        this.triId = triId;
        this.levelNo = levelNo;
    }
    

   
    // Property accessors

    public Short getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Short skillId) {
        this.skillId = skillId;
    }

    public String getTriId() {
        return this.triId;
    }
    
    public void setTriId(String triId) {
        this.triId = triId;
    }

    public Short getLevelNo() {
        return this.levelNo;
    }
    
    public void setLevelNo(Short levelNo) {
        this.levelNo = levelNo;
    }
   








}
