package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3



/**
 * SkillGrpCondRel generated by hbm2java
 */

public class SkillGrpCondRel  implements java.io.Serializable {


    // Fields    

     private SkillGrpCondRelKey comp_id;
     private Integer version;
     private SkillGroupMaster skillGrpMa;


    // Constructors

    /** default constructor */
    public SkillGrpCondRel() {
    }

	/** minimal constructor */
    public SkillGrpCondRel(SkillGrpCondRelKey comp_id) {
        this.comp_id = comp_id;
    }
    
    /** full constructor */
    public SkillGrpCondRel(SkillGrpCondRelKey comp_id, Integer version, SkillGroupMaster skillGrpMa) {
        this.comp_id = comp_id;
        this.version = version;
        this.skillGrpMa = skillGrpMa;
    }
    

   
    // Property accessors

    public SkillGrpCondRelKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(SkillGrpCondRelKey comp_id) {
        this.comp_id = comp_id;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public SkillGroupMaster getSkillGrpMa() {
        return this.skillGrpMa;
    }
    
    public void setSkillGrpMa(SkillGroupMaster skillGrpMa) {
        this.skillGrpMa = skillGrpMa;
    }
   








}
