package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3



/**
 * SkillGrpSkillRel generated by hbm2java
 */

public class SkillGrpSkillRel  implements java.io.Serializable {


    // Fields    

     private SkillGrpSkillRelKey comp_id;
     private Integer version;
     private SkillMaster skillMa;
     private SkillGroupMaster skillGrpMa;


    // Constructors

    /** default constructor */
    public SkillGrpSkillRel() {
    }

	/** minimal constructor */
    public SkillGrpSkillRel(SkillGrpSkillRelKey comp_id) {
        this.comp_id = comp_id;
    }
    
    /** full constructor */
    public SkillGrpSkillRel(SkillGrpSkillRelKey comp_id, Integer version, SkillMaster skillMa, SkillGroupMaster skillGrpMa) {
        this.comp_id = comp_id;
        this.version = version;
        this.skillMa = skillMa;
        this.skillGrpMa = skillGrpMa;
    }
    

   
    // Property accessors

    public SkillGrpSkillRelKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(SkillGrpSkillRelKey comp_id) {
        this.comp_id = comp_id;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public SkillMaster getSkillMa() {
        return this.skillMa;
    }
    
    public void setSkillMa(SkillMaster skillMa) {
        this.skillMa = skillMa;
    }

    public SkillGroupMaster getSkillGrpMa() {
        return this.skillGrpMa;
    }
    
    public void setSkillGrpMa(SkillGroupMaster skillGrpMa) {
        this.skillGrpMa = skillGrpMa;
    }
   








}
