package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3



/**
 * SkillTriRel generated by hbm2java
 */

public class SkillTriRel  implements java.io.Serializable {


    // Fields    

     private SkillTriRelKey comp_id;
     private Integer version;
     private SkillMaster skillMa;
     private TrigramMaster triMa;


    // Constructors

    /** default constructor */
    public SkillTriRel() {
    }

	/** minimal constructor */
    public SkillTriRel(SkillTriRelKey comp_id) {
        this.comp_id = comp_id;
    }
    
    /** full constructor */
    public SkillTriRel(SkillTriRelKey comp_id, Integer version, SkillMaster skillMa, TrigramMaster triMa) {
        this.comp_id = comp_id;
        this.version = version;
        this.skillMa = skillMa;
        this.triMa = triMa;
    }
    

   
    // Property accessors

    public SkillTriRelKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(SkillTriRelKey comp_id) {
        this.comp_id = comp_id;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public SkillMaster getSkillMa() {
        return this.skillMa;
    }
    
    public void setSkillMa(SkillMaster skillMa) {
        this.skillMa = skillMa;
    }

    public TrigramMaster getTriMa() {
        return this.triMa;
    }
    
    public void setTriMa(TrigramMaster triMa) {
        this.triMa = triMa;
    }
   








}
