package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:57 PM by Hibernate Tools 3.1.0 beta3



/**
 * SkillTriRelKey generated by hbm2java
 */

public class SkillTriRelKey  implements java.io.Serializable {


    // Fields    

     private Short skillId;
     private String triId;


    // Constructors

    /** default constructor */
    public SkillTriRelKey() {
    }

    
    /** full constructor */
    public SkillTriRelKey(Short skillId, String triId) {
        this.skillId = skillId;
        this.triId = triId;
    }
    

   
    // Property accessors

    public Short getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Short skillId) {
        this.skillId = skillId;
    }

    public String getTriId() {
        return this.triId;
    }
    
    public void setTriId(String triId) {
        this.triId = triId;
    }
   








}
