package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:58 PM by Hibernate Tools 3.1.0 beta3



/**
 * SkillGrpSkillRelKey generated by hbm2java
 */

public class SkillGrpSkillRelKey  implements java.io.Serializable {


    // Fields    

     private Short skillId;
     private Short skillGrpId;


    // Constructors

    /** default constructor */
    public SkillGrpSkillRelKey() {
    }

    
    /** full constructor */
    public SkillGrpSkillRelKey(Short skillId, Short skillGrpId) {
        this.skillId = skillId;
        this.skillGrpId = skillGrpId;
    }
    

   
    // Property accessors

    public Short getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Short skillId) {
        this.skillId = skillId;
    }

    public Short getSkillGrpId() {
        return this.skillGrpId;
    }
    
    public void setSkillGrpId(Short skillGrpId) {
        this.skillGrpId = skillGrpId;
    }
   








}
