package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3

import java.math.BigDecimal;


/**
 * StanScrConvMat generated by hbm2java
 */

public class StanScrConvMat  implements java.io.Serializable {


    // Fields    

     private Integer stanScrConvMatId;
     private BigDecimal rawScrLwrLmt;
     private BigDecimal rawScrUprLmt;
     private Long rawScrLwrLmtMem;
     private Long rawScrUprLmtMem;
     private BigDecimal stanScr;
     private Integer version;
     private TrigramMaster triMa;


    // Constructors

    /** default constructor */
    public StanScrConvMat() {
    }

	/** minimal constructor */
    public StanScrConvMat(Integer stanScrConvMatId, BigDecimal rawScrLwrLmt, BigDecimal stanScr) {
        this.stanScrConvMatId = stanScrConvMatId;
        this.rawScrLwrLmt = rawScrLwrLmt;
        this.stanScr = stanScr;
    }
    
    /** full constructor */
    public StanScrConvMat(Integer stanScrConvMatId, BigDecimal rawScrLwrLmt, BigDecimal rawScrUprLmt, Long rawScrLwrLmtMem, Long rawScrUprLmtMem, BigDecimal stanScr, Integer version, TrigramMaster triMa) {
        this.stanScrConvMatId = stanScrConvMatId;
        this.rawScrLwrLmt = rawScrLwrLmt;
        this.rawScrUprLmt = rawScrUprLmt;
        this.rawScrLwrLmtMem = rawScrLwrLmtMem;
        this.rawScrUprLmtMem = rawScrUprLmtMem;
        this.stanScr = stanScr;
        this.version = version;
        this.triMa = triMa;
    }
    

   
    // Property accessors

    public Integer getStanScrConvMatId() {
        return this.stanScrConvMatId;
    }
    
    public void setStanScrConvMatId(Integer stanScrConvMatId) {
        this.stanScrConvMatId = stanScrConvMatId;
    }

    public BigDecimal getRawScrLwrLmt() {
        return this.rawScrLwrLmt;
    }
    
    public void setRawScrLwrLmt(BigDecimal rawScrLwrLmt) {
        this.rawScrLwrLmt = rawScrLwrLmt;
    }

    public BigDecimal getRawScrUprLmt() {
        return this.rawScrUprLmt;
    }
    
    public void setRawScrUprLmt(BigDecimal rawScrUprLmt) {
        this.rawScrUprLmt = rawScrUprLmt;
    }

    public Long getRawScrLwrLmtMem() {
        return this.rawScrLwrLmtMem;
    }
    
    public void setRawScrLwrLmtMem(Long rawScrLwrLmtMem) {
        this.rawScrLwrLmtMem = rawScrLwrLmtMem;
    }

    public Long getRawScrUprLmtMem() {
        return this.rawScrUprLmtMem;
    }
    
    public void setRawScrUprLmtMem(Long rawScrUprLmtMem) {
        this.rawScrUprLmtMem = rawScrUprLmtMem;
    }

    public BigDecimal getStanScr() {
        return this.stanScr;
    }
    
    public void setStanScr(BigDecimal stanScr) {
        this.stanScr = stanScr;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public TrigramMaster getTriMa() {
        return this.triMa;
    }
    
    public void setTriMa(TrigramMaster triMa) {
        this.triMa = triMa;
    }
   








}
