package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:56 PM by Hibernate Tools 3.1.0 beta3

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;


/**
 * SubTestMaster generated by hbm2java
 */

public class SubTestMaster  implements java.io.Serializable {


    // Fields    

     private SubTestMasterKey comp_id;
     private BigDecimal subTestDur;
     private String path;
     private Integer version;
     private TrigramMaster triMa;
     private Set subTestCorrecTemps = new HashSet(0);
     private Set testSesScrDetNfus = new HashSet(0);
     private Set testSesScrDets = new HashSet(0);


    // Constructors

    /** default constructor */
    public SubTestMaster() {
    }

	/** minimal constructor */
    public SubTestMaster(SubTestMasterKey comp_id, String path) {
        this.comp_id = comp_id;
        this.path = path;
    }
    
    /** full constructor */
    public SubTestMaster(SubTestMasterKey comp_id, BigDecimal subTestDur, String path, Integer version, TrigramMaster triMa, Set subTestCorrecTemps, Set testSesScrDetNfus, Set testSesScrDets) {
        this.comp_id = comp_id;
        this.subTestDur = subTestDur;
        this.path = path;
        this.version = version;
        this.triMa = triMa;
        this.subTestCorrecTemps = subTestCorrecTemps;
        this.testSesScrDetNfus = testSesScrDetNfus;
        this.testSesScrDets = testSesScrDets;
    }
    

   
    // Property accessors

    public SubTestMasterKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(SubTestMasterKey comp_id) {
        this.comp_id = comp_id;
    }

    public BigDecimal getSubTestDur() {
        return this.subTestDur;
    }
    
    public void setSubTestDur(BigDecimal subTestDur) {
        this.subTestDur = subTestDur;
    }

    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public TrigramMaster getTriMa() {
        return this.triMa;
    }
    
    public void setTriMa(TrigramMaster triMa) {
        this.triMa = triMa;
    }

    public Set getSubTestCorrecTemps() {
        return this.subTestCorrecTemps;
    }
    
    public void setSubTestCorrecTemps(Set subTestCorrecTemps) {
        this.subTestCorrecTemps = subTestCorrecTemps;
    }

    public Set getTestSesScrDetNfus() {
        return this.testSesScrDetNfus;
    }
    
    public void setTestSesScrDetNfus(Set testSesScrDetNfus) {
        this.testSesScrDetNfus = testSesScrDetNfus;
    }

    public Set getTestSesScrDets() {
        return this.testSesScrDets;
    }
    
    public void setTestSesScrDets(Set testSesScrDets) {
        this.testSesScrDets = testSesScrDets;
    }
   








}
