package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:57 PM by Hibernate Tools 3.1.0 beta3



/**
 * SubTestCorrecTempKey generated by hbm2java
 */

public class SubTestCorrecTempKey  implements java.io.Serializable {


    // Fields    

     private String triId;
     private String subTestId;
     private Short quesId;
     private Short ansId;
     private String langId;


    // Constructors

    /** default constructor */
    public SubTestCorrecTempKey() {
    }

    
    /** full constructor */
    public SubTestCorrecTempKey(String triId, String subTestId, Short quesId, Short ansId, String langId) {
        this.triId = triId;
        this.subTestId = subTestId;
        this.quesId = quesId;
        this.ansId = ansId;
        this.langId = langId;
    }
    

   
    // Property accessors

    public String getTriId() {
        return this.triId;
    }
    
    public void setTriId(String triId) {
        this.triId = triId;
    }

    public String getSubTestId() {
        return this.subTestId;
    }
    
    public void setSubTestId(String subTestId) {
        this.subTestId = subTestId;
    }

    public Short getQuesId() {
        return this.quesId;
    }
    
    public void setQuesId(Short quesId) {
        this.quesId = quesId;
    }

    public Short getAnsId() {
        return this.ansId;
    }
    
    public void setAnsId(Short ansId) {
        this.ansId = ansId;
    }

    public String getLangId() {
        return this.langId;
    }
    
    public void setLangId(String langId) {
        this.langId = langId;
    }
   








}
