package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:58 PM by Hibernate Tools 3.1.0 beta3



/**
 * SubTestMasterKey generated by hbm2java
 */

public class SubTestMasterKey  implements java.io.Serializable {


    // Fields    

     private String triId;
     private String subTestId;


    // Constructors

    /** default constructor */
    public SubTestMasterKey() {
    }

    
    /** full constructor */
    public SubTestMasterKey(String triId, String subTestId) {
        this.triId = triId;
        this.subTestId = subTestId;
    }
    

   
    // Property accessors

    public String getTriId() {
        return this.triId;
    }
    
    public void setTriId(String triId) {
        this.triId = triId;
    }

    public String getSubTestId() {
        return this.subTestId;
    }
    
    public void setSubTestId(String subTestId) {
        this.subTestId = subTestId;
    }
   








}
