package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:57 PM by Hibernate Tools 3.1.0 beta3

import java.math.BigDecimal;


/**
 * SubTestCorrecTemp generated by hbm2java
 */

public class SubTestCorrecTemp  implements java.io.Serializable {


    // Fields    

     private SubTestCorrecTempKey comp_id;
     private BigDecimal marks;
     private Short seqId;
     private Short stPos;
     private Short endPos;
     private Integer version;
     private SubTestMaster subTestMa;


    // Constructors

    /** default constructor */
    public SubTestCorrecTemp() {
    }

	/** minimal constructor */
    public SubTestCorrecTemp(SubTestCorrecTempKey comp_id, BigDecimal marks) {
        this.comp_id = comp_id;
        this.marks = marks;
    }
    
    /** full constructor */
    public SubTestCorrecTemp(SubTestCorrecTempKey comp_id, BigDecimal marks, Short seqId, Short stPos, Short endPos, Integer version, SubTestMaster subTestMa) {
        this.comp_id = comp_id;
        this.marks = marks;
        this.seqId = seqId;
        this.stPos = stPos;
        this.endPos = endPos;
        this.version = version;
        this.subTestMa = subTestMa;
    }
    

   
    // Property accessors

    public SubTestCorrecTempKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(SubTestCorrecTempKey comp_id) {
        this.comp_id = comp_id;
    }

    public BigDecimal getMarks() {
        return this.marks;
    }
    
    public void setMarks(BigDecimal marks) {
        this.marks = marks;
    }

    public Short getSeqId() {
        return this.seqId;
    }
    
    public void setSeqId(Short seqId) {
        this.seqId = seqId;
    }

    public Short getStPos() {
        return this.stPos;
    }
    
    public void setStPos(Short stPos) {
        this.stPos = stPos;
    }

    public Short getEndPos() {
        return this.endPos;
    }
    
    public void setEndPos(Short endPos) {
        this.endPos = endPos;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public SubTestMaster getSubTestMa() {
        return this.subTestMa;
    }
    
    public void setSubTestMa(SubTestMaster subTestMa) {
        this.subTestMa = subTestMa;
    }
   








}
