package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:57 PM by Hibernate Tools 3.1.0 beta3

import java.math.BigDecimal;


/**
 * TestSesSkillScrDet generated by hbm2java
 */

public class TestSesSkillScrDet  implements java.io.Serializable {


    // Fields    

     private TestSesSkillScrDetKey comp_id;
     private BigDecimal skillStanScr;
     private Integer version;
     private TestSessionMaster testSesMa;
     private SkillMaster skillMa;


    // Constructors

    /** default constructor */
    public TestSesSkillScrDet() {
    }

	/** minimal constructor */
    public TestSesSkillScrDet(TestSesSkillScrDetKey comp_id, BigDecimal skillStanScr) {
        this.comp_id = comp_id;
        this.skillStanScr = skillStanScr;
    }
    
    /** full constructor */
    public TestSesSkillScrDet(TestSesSkillScrDetKey comp_id, BigDecimal skillStanScr, Integer version, TestSessionMaster testSesMa, SkillMaster skillMa) {
        this.comp_id = comp_id;
        this.skillStanScr = skillStanScr;
        this.version = version;
        this.testSesMa = testSesMa;
        this.skillMa = skillMa;
    }
    

   
    // Property accessors

    public TestSesSkillScrDetKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(TestSesSkillScrDetKey comp_id) {
        this.comp_id = comp_id;
    }

    public BigDecimal getSkillStanScr() {
        return this.skillStanScr;
    }
    
    public void setSkillStanScr(BigDecimal skillStanScr) {
        this.skillStanScr = skillStanScr;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public TestSessionMaster getTestSesMa() {
        return this.testSesMa;
    }
    
    public void setTestSesMa(TestSessionMaster testSesMa) {
        this.testSesMa = testSesMa;
    }

    public SkillMaster getSkillMa() {
        return this.skillMa;
    }
    
    public void setSkillMa(SkillMaster skillMa) {
        this.skillMa = skillMa;
    }
   








}
