package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:57 PM by Hibernate Tools 3.1.0 beta3



/**
 * TestSesScrDetNfu generated by hbm2java
 */

public class TestSesScrDetNfu  implements java.io.Serializable {


    // Fields    

     private TestSesScrDetNfuKey comp_id;
     private int sequence;
     private int deviation;
     private TestSessionMaster testSesMa;
     private SubTestMaster subTestMa;


    // Constructors

    /** default constructor */
    public TestSesScrDetNfu() {
    }

	/** minimal constructor */
    public TestSesScrDetNfu(TestSesScrDetNfuKey comp_id, int sequence, int deviation) {
        this.comp_id = comp_id;
        this.sequence = sequence;
        this.deviation = deviation;
    }
    
    /** full constructor */
    public TestSesScrDetNfu(TestSesScrDetNfuKey comp_id, int sequence, int deviation, TestSessionMaster testSesMa, SubTestMaster subTestMa) {
        this.comp_id = comp_id;
        this.sequence = sequence;
        this.deviation = deviation;
        this.testSesMa = testSesMa;
        this.subTestMa = subTestMa;
    }
    

   
    // Property accessors

    public TestSesScrDetNfuKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(TestSesScrDetNfuKey comp_id) {
        this.comp_id = comp_id;
    }

    public int getSequence() {
        return this.sequence;
    }
    
    public void setSequence(int sequence) {
        this.sequence = sequence;
    }

    public int getDeviation() {
        return this.deviation;
    }
    
    public void setDeviation(int deviation) {
        this.deviation = deviation;
    }

    public TestSessionMaster getTestSesMa() {
        return this.testSesMa;
    }
    
    public void setTestSesMa(TestSessionMaster testSesMa) {
        this.testSesMa = testSesMa;
    }

    public SubTestMaster getSubTestMa() {
        return this.subTestMa;
    }
    
    public void setSubTestMa(SubTestMaster subTestMa) {
        this.subTestMa = subTestMa;
    }
   








}
