package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:58 PM by Hibernate Tools 3.1.0 beta3



/**
 * TestSesSkillScrDetKey generated by hbm2java
 */

public class TestSesSkillScrDetKey  implements java.io.Serializable {


    // Fields    

     private String acctId;
     private Integer sesId;
     private Short skillId;


    // Constructors

    /** default constructor */
    public TestSesSkillScrDetKey() {
    }

    
    /** full constructor */
    public TestSesSkillScrDetKey(String acctId, Integer sesId, Short skillId) {
        this.acctId = acctId;
        this.sesId = sesId;
        this.skillId = skillId;
    }
    

   
    // Property accessors

    public String getAcctId() {
        return this.acctId;
    }
    
    public void setAcctId(String acctId) {
        this.acctId = acctId;
    }

    public Integer getSesId() {
        return this.sesId;
    }
    
    public void setSesId(Integer sesId) {
        this.sesId = sesId;
    }

    public Short getSkillId() {
        return this.skillId;
    }
    
    public void setSkillId(Short skillId) {
        this.skillId = skillId;
    }
   








}
