package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:57 PM by Hibernate Tools 3.1.0 beta3



/**
 * TestSesScrDetNfuKey generated by hbm2java
 */

public class TestSesScrDetNfuKey  implements java.io.Serializable {


    // Fields    

     private String acctId;
     private Integer sesId;
     private String triId;
     private String subTestId;


    // Constructors

    /** default constructor */
    public TestSesScrDetNfuKey() {
    }

    
    /** full constructor */
    public TestSesScrDetNfuKey(String acctId, Integer sesId, String triId, String subTestId) {
        this.acctId = acctId;
        this.sesId = sesId;
        this.triId = triId;
        this.subTestId = subTestId;
    }
    

   
    // Property accessors

    public String getAcctId() {
        return this.acctId;
    }
    
    public void setAcctId(String acctId) {
        this.acctId = acctId;
    }

    public Integer getSesId() {
        return this.sesId;
    }
    
    public void setSesId(Integer sesId) {
        this.sesId = sesId;
    }

    public String getTriId() {
        return this.triId;
    }
    
    public void setTriId(String triId) {
        this.triId = triId;
    }

    public String getSubTestId() {
        return this.subTestId;
    }
    
    public void setSubTestId(String subTestId) {
        this.subTestId = subTestId;
    }
   








}
