package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:58 PM by Hibernate Tools 3.1.0 beta3



/**
 * TestSessionMasterKey generated by hbm2java
 */

public class TestSessionMasterKey  implements java.io.Serializable {


    // Fields    

     private String acctId;
     private Integer sesId;


    // Constructors

    /** default constructor */
    public TestSessionMasterKey() {
    }

    
    /** full constructor */
    public TestSessionMasterKey(String acctId, Integer sesId) {
        this.acctId = acctId;
        this.sesId = sesId;
    }
    

   
    // Property accessors

    public String getAcctId() {
        return this.acctId;
    }
    
    public void setAcctId(String acctId) {
        this.acctId = acctId;
    }

    public Integer getSesId() {
        return this.sesId;
    }
    
    public void setSesId(Integer sesId) {
        this.sesId = sesId;
    }
   








}
