package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:57 PM by Hibernate Tools 3.1.0 beta3

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;


/**
 * TestSessionMaster generated by hbm2java
 */

public class TestSessionMaster  implements java.io.Serializable {


    // Fields    

     private TestSessionMasterKey comp_id;
     private String usrId;
     private String compFlg;
     private Integer timesAnserChanged;
     private Integer timesExpired;
     private Timestamp dtStart;
     private Timestamp dtEnd;
     private Integer version;
     private AcctMaster acctMa;
     private Set testSesScrDetNfus = new HashSet(0);
     private Set testSesSkillScrDets = new HashSet(0);
     private Set testSesScrDets = new HashSet(0);


    // Constructors

    /** default constructor */
    public TestSessionMaster() {
    }

	/** minimal constructor */
    public TestSessionMaster(TestSessionMasterKey comp_id, String usrId, Timestamp dtStart) {
        this.comp_id = comp_id;
        this.usrId = usrId;
        this.dtStart = dtStart;
    }
    
    /** full constructor */
    public TestSessionMaster(TestSessionMasterKey comp_id, String usrId, String compFlg, Integer timesAnserChanged, Integer timesExpired, Timestamp dtStart, Timestamp dtEnd, Integer version, AcctMaster acctMa, Set testSesScrDetNfus, Set testSesSkillScrDets, Set testSesScrDets) {
        this.comp_id = comp_id;
        this.usrId = usrId;
        this.compFlg = compFlg;
        this.timesAnserChanged = timesAnserChanged;
        this.timesExpired = timesExpired;
        this.dtStart = dtStart;
        this.dtEnd = dtEnd;
        this.version = version;
        this.acctMa = acctMa;
        this.testSesScrDetNfus = testSesScrDetNfus;
        this.testSesSkillScrDets = testSesSkillScrDets;
        this.testSesScrDets = testSesScrDets;
    }
    

   
    // Property accessors

    public TestSessionMasterKey getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(TestSessionMasterKey comp_id) {
        this.comp_id = comp_id;
    }

    public String getUsrId() {
        return this.usrId;
    }
    
    public void setUsrId(String usrId) {
        this.usrId = usrId;
    }

    public String getCompFlg() {
        return this.compFlg;
    }
    
    public void setCompFlg(String compFlg) {
        this.compFlg = compFlg;
    }

    public Integer getTimesAnserChanged() {
        return this.timesAnserChanged;
    }
    
    public void setTimesAnserChanged(Integer timesAnserChanged) {
        this.timesAnserChanged = timesAnserChanged;
    }

    public Integer getTimesExpired() {
        return this.timesExpired;
    }
    
    public void setTimesExpired(Integer timesExpired) {
        this.timesExpired = timesExpired;
    }

    public Timestamp getDtStart() {
        return this.dtStart;
    }
    
    public void setDtStart(Timestamp dtStart) {
        this.dtStart = dtStart;
    }

    public Timestamp getDtEnd() {
        return this.dtEnd;
    }
    
    public void setDtEnd(Timestamp dtEnd) {
        this.dtEnd = dtEnd;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public AcctMaster getAcctMa() {
        return this.acctMa;
    }
    
    public void setAcctMa(AcctMaster acctMa) {
        this.acctMa = acctMa;
    }

    public Set getTestSesScrDetNfus() {
        return this.testSesScrDetNfus;
    }
    
    public void setTestSesScrDetNfus(Set testSesScrDetNfus) {
        this.testSesScrDetNfus = testSesScrDetNfus;
    }

    public Set getTestSesSkillScrDets() {
        return this.testSesSkillScrDets;
    }
    
    public void setTestSesSkillScrDets(Set testSesSkillScrDets) {
        this.testSesSkillScrDets = testSesSkillScrDets;
    }

    public Set getTestSesScrDets() {
        return this.testSesScrDets;
    }
    
    public void setTestSesScrDets(Set testSesScrDets) {
        this.testSesScrDets = testSesScrDets;
    }
   








}
