package com.mgmtassessment.execmap.data.dao.types;
// Generated Aug 3, 2006 6:56:57 PM by Hibernate Tools 3.1.0 beta3

import java.util.HashSet;
import java.util.Set;


/**
 * TrigramMaster generated by hbm2java
 */

public class TrigramMaster  implements java.io.Serializable {


    // Fields    

     private String triId;
     private String whatIsTst;
     private String whatItImpc;
     private String visIndc;
     private String triDesc;
     private short actSeqNum;
     private Integer version;
     private Set subTestMas = new HashSet(0);
     private Set skillTriRels = new HashSet(0);
     private Set stanScrConvMats = new HashSet(0);
     private Set skillLvlTriRels = new HashSet(0);


    // Constructors

    /** default constructor */
    public TrigramMaster() {
    }

	/** minimal constructor */
    public TrigramMaster(String triId, String triDesc, short actSeqNum) {
        this.triId = triId;
        this.triDesc = triDesc;
        this.actSeqNum = actSeqNum;
    }
    
    /** full constructor */
    public TrigramMaster(String triId, String whatIsTst, String whatItImpc, String visIndc, String triDesc, short actSeqNum, Integer version, Set subTestMas, Set skillTriRels, Set stanScrConvMats, Set skillLvlTriRels) {
        this.triId = triId;
        this.whatIsTst = whatIsTst;
        this.whatItImpc = whatItImpc;
        this.visIndc = visIndc;
        this.triDesc = triDesc;
        this.actSeqNum = actSeqNum;
        this.version = version;
        this.subTestMas = subTestMas;
        this.skillTriRels = skillTriRels;
        this.stanScrConvMats = stanScrConvMats;
        this.skillLvlTriRels = skillLvlTriRels;
    }
    

   
    // Property accessors

    public String getTriId() {
        return this.triId;
    }
    
    public void setTriId(String triId) {
        this.triId = triId;
    }

    public String getWhatIsTst() {
        return this.whatIsTst;
    }
    
    public void setWhatIsTst(String whatIsTst) {
        this.whatIsTst = whatIsTst;
    }

    public String getWhatItImpc() {
        return this.whatItImpc;
    }
    
    public void setWhatItImpc(String whatItImpc) {
        this.whatItImpc = whatItImpc;
    }

    public String getVisIndc() {
        return this.visIndc;
    }
    
    public void setVisIndc(String visIndc) {
        this.visIndc = visIndc;
    }

    public String getTriDesc() {
        return this.triDesc;
    }
    
    public void setTriDesc(String triDesc) {
        this.triDesc = triDesc;
    }

    public short getActSeqNum() {
        return this.actSeqNum;
    }
    
    public void setActSeqNum(short actSeqNum) {
        this.actSeqNum = actSeqNum;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set getSubTestMas() {
        return this.subTestMas;
    }
    
    public void setSubTestMas(Set subTestMas) {
        this.subTestMas = subTestMas;
    }

    public Set getSkillTriRels() {
        return this.skillTriRels;
    }
    
    public void setSkillTriRels(Set skillTriRels) {
        this.skillTriRels = skillTriRels;
    }

    public Set getStanScrConvMats() {
        return this.stanScrConvMats;
    }
    
    public void setStanScrConvMats(Set stanScrConvMats) {
        this.stanScrConvMats = stanScrConvMats;
    }

    public Set getSkillLvlTriRels() {
        return this.skillLvlTriRels;
    }
    
    public void setSkillLvlTriRels(Set skillLvlTriRels) {
        this.skillLvlTriRels = skillLvlTriRels;
    }
   








}
