/**
 *  @Copyright Management Assessment Partners (MAP) AG
 *  All Rights Reserved.
 *
 *  @Author : TODO
 *  @Date   : Jul 7, 2006
 *
 * TODO add description for this class
 *
 */

package com.mgmtassessment.execmap.webapp.main.globalsettings.form;

import com.mgmtassessment.execmap.business.model.GlobalSettingsModel;
import com.mgmtassessment.execmap.business.model.UserAccountModel;
import com.mgmtassessment.execmap.common.framework.webapp.ExecmapForm;

import java.io.Serializable;

public class GlobalSettingsForm extends ExecmapForm implements Serializable {

    private GlobalSettingsModel globalSettingsModel = new GlobalSettingsModel();

    /**
     * sysmasid
     */
    private String sysMasId;

    /**
     * last account no generated by the aplication
     */

    private String lstAcctNo;

    /**
     * time alloted for the test's
     */
    private String testDur;

    /**
     * accountId for the intellicue admin
     */

    private String intlcAcctId;

    /**
     * global manager userId
     */

    private String intlcUsrId;

    /**
     * password for the global manager
     */

    private String intlcPasswd;

    /**
     * the email server name
     */

    private String emailServerName;

    /**
     * the port no at which email server runs
     */

    private String emailServerPort;

    /**
     * userId to access email server
     */

    private String emailServerUserid;

    /**
     * password to access email server
     */

    private String emailServerPassword;

    private String version;

    /**
     * @return Returns the globalSettingsModel.
     */
    public GlobalSettingsModel getGlobalSettingsModel() {
        return globalSettingsModel;
    }

    /**
     * @param globalSettingsModel
     *            The globalSettingsModel to set.
     */
    public void setGlobalSettingsModel(GlobalSettingsModel globalSettingsModel) {
        this.globalSettingsModel = globalSettingsModel;
    }

    /**
     * @return Returns the emailServerName.
     */
    public String getEmailServerName() {
        return emailServerName;
    }

    /**
     * @param emailServerName
     *            The emailServerName to set.
     */
    public void setEmailServerName(String emailServerName) {
        this.emailServerName = emailServerName;
    }

    /**
     * @return Returns the emailServerPassword.
     */
    public String getEmailServerPassword() {
        return emailServerPassword;
    }

    /**
     * @param emailServerPassword
     *            The emailServerPassword to set.
     */
    public void setEmailServerPassword(String emailServerPassword) {
        this.emailServerPassword = emailServerPassword;
    }

    /**
     * @return Returns the emailServerPort.
     */
    public String getEmailServerPort() {
        return emailServerPort;
    }

    /**
     * @param emailServerPort
     *            The emailServerPort to set.
     */
    public void setEmailServerPort(String emailServerPort) {
        this.emailServerPort = emailServerPort;
    }

    /**
     * @return Returns the emailServerUserid.
     */
    public String getEmailServerUserid() {
        return emailServerUserid;
    }

    /**
     * @param emailServerUserid
     *            The emailServerUserid to set.
     */
    public void setEmailServerUserid(String emailServerUserid) {
        this.emailServerUserid = emailServerUserid;
    }

    /**
     * @return Returns the intlcAcctId.
     */
    public String getIntlcAcctId() {
        return intlcAcctId;
    }

    /**
     * @param intlcAcctId
     *            The intlcAcctId to set.
     */
    public void setIntlcAcctId(String intlcAcctId) {
        this.intlcAcctId = intlcAcctId;
    }

    /**
     * @return Returns the intlcPasswd.
     */
    public String getIntlcPasswd() {
        return intlcPasswd;
    }

    /**
     * @param intlcPasswd
     *            The intlcPasswd to set.
     */
    public void setIntlcPasswd(String intlcPasswd) {
        this.intlcPasswd = intlcPasswd;
    }

    /**
     * @return Returns the intlcUsrId.
     */
    public String getIntlcUsrId() {
        return intlcUsrId;
    }

    /**
     * @param intlcUsrId
     *            The intlcUsrId to set.
     */
    public void setIntlcUsrId(String intlcUsrId) {
        this.intlcUsrId = intlcUsrId;
    }

    /**
     * @return Returns the lstAcctNo.
     */
    public String getLstAcctNo() {
        return lstAcctNo;
    }

    /**
     * @param lstAcctNo
     *            The lstAcctNo to set.
     */
    public void setLstAcctNo(String lstAcctNo) {
        this.lstAcctNo = lstAcctNo;
    }

    /**
     * @return Returns the sysMasId.
     */
    public String getSysMasId() {
        return sysMasId;
    }

    /**
     * @param sysMasId
     *            The sysMasId to set.
     */
    public void setSysMasId(String sysMasId) {
        this.sysMasId = sysMasId;
    }

    /**
     * @return Returns the testDur.
     */
    public String getTestDur() {
        return testDur;
    }

    /**
     * @param testDur
     *            The testDur to set.
     */
    public void setTestDur(String testDur) {
        this.testDur = testDur;
    }

    /**
     * @return Returns the version.
     */
    public String getVersion() {
        return version;
    }

    /**
     * @param version
     *            The version to set.
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method populates the form with the required values from the model
     * object
     * 
     * @param userAccountModel
     */
    public void populateForm(GlobalSettingsModel globalSettingsModel) {

        sysMasId = "" + globalSettingsModel.getSysMasId();

        lstAcctNo = "" + globalSettingsModel.getLstAcctNo();

        testDur = "" + globalSettingsModel.getTestDur();

        intlcAcctId = globalSettingsModel.getIntlcAcctId();

        intlcUsrId = globalSettingsModel.getGlobalMngrUserId();

        intlcPasswd = globalSettingsModel.getGlobalMngrPwd();

        emailServerName = globalSettingsModel.getExchServerName();

        emailServerPort = globalSettingsModel.getExchServerPortNo();

        emailServerUserid = globalSettingsModel.getExchServerUserId();

        emailServerPassword = globalSettingsModel.getExchServerPwd();

    }

}
